### ISSUE TITLE
Add real swiping (like in App Store)

### ISSUE THREAD

**Issue by mariuskueng** [bbjay/jquery-inline-slides#9]
Example: (20min.ch mobile page)

**Comment by bbjay** [comment]
I don't think that's possible with touchwipe. 
Do you know another jQuery plug in that would allow this feature?

**Comment by mariuskueng** [comment]
Yes, I know that this is not possible with touchwipe.
Nope, it's just an suggestion. First I have to look if there is anything.

**Comment by mariuskueng** [comment]
Maybe one of these is useful. Didn't try them out yet though.

http://www.photoswipe.com/
http://www.app-agentur-bw.de/showcase/swipegallery
**https://github.com/bradbirdsall/Swipe/**

**http://cubiq.org/iscroll-4**
http://www.zackgrossbart.com/hackito/touchslider/
jqueryUI Carousel
